# Generated by Django 5.1 on 2024-08-31 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descricao',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cadegoria',
        ),
    ]
