# Generated by Django 5.1.2 on 2024-10-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_texto_post_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('conteudo', models.TextField(max_length=1200)),
            ],
        ),
    ]
