# Generated by Django 5.1.2 on 2024-10-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
